// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

import type {} from '@useautumn/sdk';

declare module '@useautumn/sdk' {
  // Features
  export const ai_credits: Feature;

  // Plans
  export const free: Plan;
  export const pro: Plan;
  export const credit_pack_5: Plan;
  export const credit_pack_25: Plan;
  export const credit_pack_100: Plan;
  export const credit_pack_10: Plan;

  // Base types
  export type Feature = import('./autumn.config').Feature;
  export type Plan = import('./autumn.config').Plan;
}
