/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchedRouteImport } from './routes/vouched'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppOrgHandleRouteImport } from './routes/_app/$orgHandle'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerRouteImport } from './routes/[.well-known]/oauth-authorization-server'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as RequestOwnerRepoRouteImport } from './routes/request.$owner.$repo'
import { Route as ApiV1VouchedRouteImport } from './routes/api/v1/vouched'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiToolsRunRouteImport } from './routes/api/tools/run'
import { Route as ApiOauthAppInfoRouteImport } from './routes/api/oauth/app-info'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github/install'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersUsernameRouteImport } from './routes/_app/users/$username'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSettingsDevelopersRouteImport } from './routes/_app/settings/developers'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events/$eventId'
import { Route as AppChatChatIdRouteImport } from './routes/_app/chat/$chatId'
import { Route as AppOrgHandleRulesRouteImport } from './routes/_app/$orgHandle/rules'
import { Route as AppOrgHandleIntegrationsRouteImport } from './routes/_app/$orgHandle/integrations'
import { Route as AppOrgHandleInsightsRouteImport } from './routes/_app/$orgHandle/insights'
import { Route as AppOrgHandleHomeRouteImport } from './routes/_app/$orgHandle/home'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceSplatRouteImport } from './routes/[.well-known]/oauth-protected-resource/$'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerSplatRouteImport } from './routes/[.well-known]/oauth-authorization-server/$'
import { Route as AppOrgHandleEventsIndexRouteImport } from './routes/_app/$orgHandle/events/index'
import { Route as AppOrgHandleAutomationsIndexRouteImport } from './routes/_app/$orgHandle/automations/index'
import { Route as AppOrgHandleEventsEventIdRouteImport } from './routes/_app/$orgHandle/events/$eventId'
import { Route as AppOrgHandleAutomationsPreviewRouteImport } from './routes/_app/$orgHandle/automations/preview'
import { Route as AppOrgHandleAutomationsAutomationIdRouteImport } from './routes/_app/$orgHandle/automations/$automationId'

const VouchedRoute = VouchedRouteImport.update({
  id: '/vouched',
  path: '/vouched',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgHandleRoute = AppOrgHandleRouteImport.update({
  id: '/$orgHandle',
  path: '/$orgHandle',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthAuthorizationServerRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const RequestOwnerRepoRoute = RequestOwnerRepoRouteImport.update({
  id: '/request/$owner/$repo',
  path: '/request/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VouchedRoute = ApiV1VouchedRouteImport.update({
  id: '/api/v1/vouched',
  path: '/api/v1/vouched',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsRunRoute = ApiToolsRunRouteImport.update({
  id: '/api/tools/run',
  path: '/api/tools/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthAppInfoRoute = ApiOauthAppInfoRouteImport.update({
  id: '/api/oauth/app-info',
  path: '/api/oauth/app-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUsernameRoute = AppUsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDevelopersRoute = AppSettingsDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgHandleRulesRoute = AppOrgHandleRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AppOrgHandleIntegrationsRoute =
  AppOrgHandleIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AppOrgHandleInsightsRoute = AppOrgHandleInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AppOrgHandleHomeRoute = AppOrgHandleHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceSplatRoute =
  Char91DotwellKnownChar93OauthProtectedResourceSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char91DotwellKnownChar93OauthProtectedResourceRoute,
  } as any)
const Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char91DotwellKnownChar93OauthAuthorizationServerRoute,
  } as any)
const AppOrgHandleEventsIndexRoute = AppOrgHandleEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AppOrgHandleAutomationsIndexRoute =
  AppOrgHandleAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AppOrgHandleEventsEventIdRoute =
  AppOrgHandleEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AppOrgHandleAutomationsPreviewRoute =
  AppOrgHandleAutomationsPreviewRouteImport.update({
    id: '/automations/preview',
    path: '/automations/preview',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AppOrgHandleAutomationsAutomationIdRoute =
  AppOrgHandleAutomationsAutomationIdRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vouched': typeof VouchedRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren
  '/$orgHandle': typeof AppOrgHandleRouteWithChildren
  '/automations': typeof AppAutomationsRoute
  '/home': typeof AppHomeRoute
  '/insights': typeof AppInsightsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRoute
  '/$orgHandle/home': typeof AppOrgHandleHomeRoute
  '/$orgHandle/insights': typeof AppOrgHandleInsightsRoute
  '/$orgHandle/integrations': typeof AppOrgHandleIntegrationsRoute
  '/$orgHandle/rules': typeof AppOrgHandleRulesRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/developers': typeof AppSettingsDevelopersRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/app-info': typeof ApiOauthAppInfoRoute
  '/api/tools/run': typeof ApiToolsRunRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/vouched': typeof ApiV1VouchedRoute
  '/request/$owner/$repo': typeof RequestOwnerRepoRoute
  '/events/': typeof AppEventsIndexRoute
  '/$orgHandle/automations/$automationId': typeof AppOrgHandleAutomationsAutomationIdRoute
  '/$orgHandle/automations/preview': typeof AppOrgHandleAutomationsPreviewRoute
  '/$orgHandle/events/$eventId': typeof AppOrgHandleEventsEventIdRoute
  '/$orgHandle/automations/': typeof AppOrgHandleAutomationsIndexRoute
  '/$orgHandle/events/': typeof AppOrgHandleEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vouched': typeof VouchedRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren
  '/$orgHandle': typeof AppOrgHandleRouteWithChildren
  '/automations': typeof AppAutomationsRoute
  '/home': typeof AppHomeRoute
  '/insights': typeof AppInsightsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRoute
  '/$orgHandle/home': typeof AppOrgHandleHomeRoute
  '/$orgHandle/insights': typeof AppOrgHandleInsightsRoute
  '/$orgHandle/integrations': typeof AppOrgHandleIntegrationsRoute
  '/$orgHandle/rules': typeof AppOrgHandleRulesRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/developers': typeof AppSettingsDevelopersRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/app-info': typeof ApiOauthAppInfoRoute
  '/api/tools/run': typeof ApiToolsRunRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/vouched': typeof ApiV1VouchedRoute
  '/request/$owner/$repo': typeof RequestOwnerRepoRoute
  '/events': typeof AppEventsIndexRoute
  '/$orgHandle/automations/$automationId': typeof AppOrgHandleAutomationsAutomationIdRoute
  '/$orgHandle/automations/preview': typeof AppOrgHandleAutomationsPreviewRoute
  '/$orgHandle/events/$eventId': typeof AppOrgHandleEventsEventIdRoute
  '/$orgHandle/automations': typeof AppOrgHandleAutomationsIndexRoute
  '/$orgHandle/events': typeof AppOrgHandleEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/vouched': typeof VouchedRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren
  '/_app/$orgHandle': typeof AppOrgHandleRouteWithChildren
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRoute
  '/_app/$orgHandle/home': typeof AppOrgHandleHomeRoute
  '/_app/$orgHandle/insights': typeof AppOrgHandleInsightsRoute
  '/_app/$orgHandle/integrations': typeof AppOrgHandleIntegrationsRoute
  '/_app/$orgHandle/rules': typeof AppOrgHandleRulesRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/developers': typeof AppSettingsDevelopersRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/app-info': typeof ApiOauthAppInfoRoute
  '/api/tools/run': typeof ApiToolsRunRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/vouched': typeof ApiV1VouchedRoute
  '/request/$owner/$repo': typeof RequestOwnerRepoRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/$orgHandle/automations/$automationId': typeof AppOrgHandleAutomationsAutomationIdRoute
  '/_app/$orgHandle/automations/preview': typeof AppOrgHandleAutomationsPreviewRoute
  '/_app/$orgHandle/events/$eventId': typeof AppOrgHandleEventsEventIdRoute
  '/_app/$orgHandle/automations/': typeof AppOrgHandleAutomationsIndexRoute
  '/_app/$orgHandle/events/': typeof AppOrgHandleEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/vouched'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/$orgHandle'
    | '/automations'
    | '/home'
    | '/insights'
    | '/integrations'
    | '/rules'
    | '/search'
    | '/settings'
    | '/api/chat'
    | '/api/mcp'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/$orgHandle/home'
    | '/$orgHandle/insights'
    | '/$orgHandle/integrations'
    | '/$orgHandle/rules'
    | '/chat/$chatId'
    | '/events/$eventId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/developers'
    | '/settings/general'
    | '/users/$username'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/oauth/app-info'
    | '/api/tools/run'
    | '/api/trpc/$'
    | '/api/v1/vouched'
    | '/request/$owner/$repo'
    | '/events/'
    | '/$orgHandle/automations/$automationId'
    | '/$orgHandle/automations/preview'
    | '/$orgHandle/events/$eventId'
    | '/$orgHandle/automations/'
    | '/$orgHandle/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/vouched'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/$orgHandle'
    | '/automations'
    | '/home'
    | '/insights'
    | '/integrations'
    | '/rules'
    | '/search'
    | '/settings'
    | '/api/chat'
    | '/api/mcp'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/$orgHandle/home'
    | '/$orgHandle/insights'
    | '/$orgHandle/integrations'
    | '/$orgHandle/rules'
    | '/chat/$chatId'
    | '/events/$eventId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/developers'
    | '/settings/general'
    | '/users/$username'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/oauth/app-info'
    | '/api/tools/run'
    | '/api/trpc/$'
    | '/api/v1/vouched'
    | '/request/$owner/$repo'
    | '/events'
    | '/$orgHandle/automations/$automationId'
    | '/$orgHandle/automations/preview'
    | '/$orgHandle/events/$eventId'
    | '/$orgHandle/automations'
    | '/$orgHandle/events'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/vouched'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_app/$orgHandle'
    | '/_app/automations'
    | '/_app/home'
    | '/_app/insights'
    | '/_app/integrations'
    | '/_app/rules'
    | '/_app/search'
    | '/_app/settings'
    | '/api/chat'
    | '/api/mcp'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/_app/$orgHandle/home'
    | '/_app/$orgHandle/insights'
    | '/_app/$orgHandle/integrations'
    | '/_app/$orgHandle/rules'
    | '/_app/chat/$chatId'
    | '/_app/events/$eventId'
    | '/_app/settings/account'
    | '/_app/settings/billing'
    | '/_app/settings/developers'
    | '/_app/settings/general'
    | '/_app/users/$username'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/oauth/app-info'
    | '/api/tools/run'
    | '/api/trpc/$'
    | '/api/v1/vouched'
    | '/request/$owner/$repo'
    | '/_app/events/'
    | '/_app/$orgHandle/automations/$automationId'
    | '/_app/$orgHandle/automations/preview'
    | '/_app/$orgHandle/events/$eventId'
    | '/_app/$orgHandle/automations/'
    | '/_app/$orgHandle/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  VouchedRoute: typeof VouchedRoute
  Char91DotwellKnownChar93OauthAuthorizationServerRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiMcpRoute: typeof ApiMcpRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiOauthAppInfoRoute: typeof ApiOauthAppInfoRoute
  ApiToolsRunRoute: typeof ApiToolsRunRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiV1VouchedRoute: typeof ApiV1VouchedRoute
  RequestOwnerRepoRoute: typeof RequestOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouched': {
      id: '/vouched'
      path: '/vouched'
      fullPath: '/vouched'
      preLoaderRoute: typeof VouchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgHandle': {
      id: '/_app/$orgHandle'
      path: '/$orgHandle'
      fullPath: '/$orgHandle'
      preLoaderRoute: typeof AppOrgHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/request/$owner/$repo': {
      id: '/request/$owner/$repo'
      path: '/request/$owner/$repo'
      fullPath: '/request/$owner/$repo'
      preLoaderRoute: typeof RequestOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/vouched': {
      id: '/api/v1/vouched'
      path: '/api/v1/vouched'
      fullPath: '/api/v1/vouched'
      preLoaderRoute: typeof ApiV1VouchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/run': {
      id: '/api/tools/run'
      path: '/api/tools/run'
      fullPath: '/api/tools/run'
      preLoaderRoute: typeof ApiToolsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/app-info': {
      id: '/api/oauth/app-info'
      path: '/api/oauth/app-info'
      fullPath: '/api/oauth/app-info'
      preLoaderRoute: typeof ApiOauthAppInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/$username': {
      id: '/_app/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AppUsersUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/developers': {
      id: '/_app/settings/developers'
      path: '/developers'
      fullPath: '/settings/developers'
      preLoaderRoute: typeof AppSettingsDevelopersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgHandle/rules': {
      id: '/_app/$orgHandle/rules'
      path: '/rules'
      fullPath: '/$orgHandle/rules'
      preLoaderRoute: typeof AppOrgHandleRulesRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/integrations': {
      id: '/_app/$orgHandle/integrations'
      path: '/integrations'
      fullPath: '/$orgHandle/integrations'
      preLoaderRoute: typeof AppOrgHandleIntegrationsRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/insights': {
      id: '/_app/$orgHandle/insights'
      path: '/insights'
      fullPath: '/$orgHandle/insights'
      preLoaderRoute: typeof AppOrgHandleInsightsRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/home': {
      id: '/_app/$orgHandle/home'
      path: '/home'
      fullPath: '/$orgHandle/home'
      preLoaderRoute: typeof AppOrgHandleHomeRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/.well-known/oauth-protected-resource/$': {
      id: '/.well-known/oauth-protected-resource/$'
      path: '/$'
      fullPath: '/.well-known/oauth-protected-resource/$'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRouteImport
      parentRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
    }
    '/.well-known/oauth-authorization-server/$': {
      id: '/.well-known/oauth-authorization-server/$'
      path: '/$'
      fullPath: '/.well-known/oauth-authorization-server/$'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRouteImport
      parentRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
    }
    '/_app/$orgHandle/events/': {
      id: '/_app/$orgHandle/events/'
      path: '/events'
      fullPath: '/$orgHandle/events/'
      preLoaderRoute: typeof AppOrgHandleEventsIndexRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/automations/': {
      id: '/_app/$orgHandle/automations/'
      path: '/automations'
      fullPath: '/$orgHandle/automations/'
      preLoaderRoute: typeof AppOrgHandleAutomationsIndexRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/events/$eventId': {
      id: '/_app/$orgHandle/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/$orgHandle/events/$eventId'
      preLoaderRoute: typeof AppOrgHandleEventsEventIdRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/automations/preview': {
      id: '/_app/$orgHandle/automations/preview'
      path: '/automations/preview'
      fullPath: '/$orgHandle/automations/preview'
      preLoaderRoute: typeof AppOrgHandleAutomationsPreviewRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/automations/$automationId': {
      id: '/_app/$orgHandle/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/$orgHandle/automations/$automationId'
      preLoaderRoute: typeof AppOrgHandleAutomationsAutomationIdRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
  }
}

interface AppOrgHandleRouteChildren {
  AppOrgHandleHomeRoute: typeof AppOrgHandleHomeRoute
  AppOrgHandleInsightsRoute: typeof AppOrgHandleInsightsRoute
  AppOrgHandleIntegrationsRoute: typeof AppOrgHandleIntegrationsRoute
  AppOrgHandleRulesRoute: typeof AppOrgHandleRulesRoute
  AppOrgHandleAutomationsAutomationIdRoute: typeof AppOrgHandleAutomationsAutomationIdRoute
  AppOrgHandleAutomationsPreviewRoute: typeof AppOrgHandleAutomationsPreviewRoute
  AppOrgHandleEventsEventIdRoute: typeof AppOrgHandleEventsEventIdRoute
  AppOrgHandleAutomationsIndexRoute: typeof AppOrgHandleAutomationsIndexRoute
  AppOrgHandleEventsIndexRoute: typeof AppOrgHandleEventsIndexRoute
}

const AppOrgHandleRouteChildren: AppOrgHandleRouteChildren = {
  AppOrgHandleHomeRoute: AppOrgHandleHomeRoute,
  AppOrgHandleInsightsRoute: AppOrgHandleInsightsRoute,
  AppOrgHandleIntegrationsRoute: AppOrgHandleIntegrationsRoute,
  AppOrgHandleRulesRoute: AppOrgHandleRulesRoute,
  AppOrgHandleAutomationsAutomationIdRoute:
    AppOrgHandleAutomationsAutomationIdRoute,
  AppOrgHandleAutomationsPreviewRoute: AppOrgHandleAutomationsPreviewRoute,
  AppOrgHandleEventsEventIdRoute: AppOrgHandleEventsEventIdRoute,
  AppOrgHandleAutomationsIndexRoute: AppOrgHandleAutomationsIndexRoute,
  AppOrgHandleEventsIndexRoute: AppOrgHandleEventsIndexRoute,
}

const AppOrgHandleRouteWithChildren = AppOrgHandleRoute._addFileChildren(
  AppOrgHandleRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsDevelopersRoute: typeof AppSettingsDevelopersRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsDevelopersRoute: AppSettingsDevelopersRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppOrgHandleRoute: typeof AppOrgHandleRouteWithChildren
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppChatChatIdRoute: typeof AppChatChatIdRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppUsersUsernameRoute: typeof AppUsersUsernameRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgHandleRoute: AppOrgHandleRouteWithChildren,
  AppAutomationsRoute: AppAutomationsRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppRulesRoute: AppRulesRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppChatChatIdRoute: AppChatChatIdRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppUsersUsernameRoute: AppUsersUsernameRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface Char91DotwellKnownChar93OauthAuthorizationServerRouteChildren {
  Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute
}

const Char91DotwellKnownChar93OauthAuthorizationServerRouteChildren: Char91DotwellKnownChar93OauthAuthorizationServerRouteChildren =
  {
    Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute:
      Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute,
  }

const Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren =
  Char91DotwellKnownChar93OauthAuthorizationServerRoute._addFileChildren(
    Char91DotwellKnownChar93OauthAuthorizationServerRouteChildren,
  )

interface Char91DotwellKnownChar93OauthProtectedResourceRouteChildren {
  Char91DotwellKnownChar93OauthProtectedResourceSplatRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRoute
}

const Char91DotwellKnownChar93OauthProtectedResourceRouteChildren: Char91DotwellKnownChar93OauthProtectedResourceRouteChildren =
  {
    Char91DotwellKnownChar93OauthProtectedResourceSplatRoute:
      Char91DotwellKnownChar93OauthProtectedResourceSplatRoute,
  }

const Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren =
  Char91DotwellKnownChar93OauthProtectedResourceRoute._addFileChildren(
    Char91DotwellKnownChar93OauthProtectedResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  VouchedRoute: VouchedRoute,
  Char91DotwellKnownChar93OauthAuthorizationServerRoute:
    Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiMcpRoute: ApiMcpRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubInstallRoute: ApiGithubInstallRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiOauthAppInfoRoute: ApiOauthAppInfoRoute,
  ApiToolsRunRoute: ApiToolsRunRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiV1VouchedRoute: ApiV1VouchedRoute,
  RequestOwnerRepoRoute: RequestOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
