/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchedRouteImport } from './routes/vouched'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppVisibilityRouteImport } from './routes/_app/visibility'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppOrgHandleRouteImport } from './routes/_app/$orgHandle'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerRouteImport } from './routes/[.well-known]/oauth-authorization-server'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as RequestOwnerRepoRouteImport } from './routes/request.$owner.$repo'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding/step.4'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding/step.3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step.2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step.1'
import { Route as ApiV1VouchedRouteImport } from './routes/api/v1/vouched'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiToolsRunRouteImport } from './routes/api/tools/run'
import { Route as ApiOauthAppInfoRouteImport } from './routes/api/oauth/app-info'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github/install'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiDevLoginRouteImport } from './routes/api/dev/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersUsernameRouteImport } from './routes/_app/users/$username'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSettingsDevelopersRouteImport } from './routes/_app/settings/developers'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events/$eventId'
import { Route as AppChatChatIdRouteImport } from './routes/_app/chat/$chatId'
import { Route as AppOrgHandleVisibilityRouteImport } from './routes/_app/$orgHandle/visibility'
import { Route as AppOrgHandleSettingsRouteImport } from './routes/_app/$orgHandle/settings'
import { Route as AppOrgHandleIntegrationsRouteImport } from './routes/_app/$orgHandle/integrations'
import { Route as AppOrgHandleInsightsRouteImport } from './routes/_app/$orgHandle/insights'
import { Route as AppOrgHandleHomeRouteImport } from './routes/_app/$orgHandle/home'
import { Route as AdminAdminReputationRouteImport } from './routes/_admin/admin/reputation'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceSplatRouteImport } from './routes/[.well-known]/oauth-protected-resource/$'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerSplatRouteImport } from './routes/[.well-known]/oauth-authorization-server/$'
import { Route as AppOrgHandleRulesRouteRouteImport } from './routes/_app/$orgHandle/rules/route'
import { Route as AppOrgHandleRulesIndexRouteImport } from './routes/_app/$orgHandle/rules/index'
import { Route as AppOrgHandleEventsIndexRouteImport } from './routes/_app/$orgHandle/events/index'
import { Route as AppOrgHandleAutomationsIndexRouteImport } from './routes/_app/$orgHandle/automations/index'
import { Route as AdminAdminResearchIndexRouteImport } from './routes/_admin/admin/research/index'
import { Route as ApiGithubSignalsStreamRouteImport } from './routes/api/github/signals/stream'
import { Route as AppOrgHandleRulesWorkflowsRouteImport } from './routes/_app/$orgHandle/rules/workflows'
import { Route as AppOrgHandleRulesRequestsRouteImport } from './routes/_app/$orgHandle/rules/requests'
import { Route as AppOrgHandleRulesPeopleRouteImport } from './routes/_app/$orgHandle/rules/people'
import { Route as AppOrgHandleRulesMarketplaceRouteImport } from './routes/_app/$orgHandle/rules/marketplace'
import { Route as AppOrgHandleRulesInstalledRouteImport } from './routes/_app/$orgHandle/rules/installed'
import { Route as AppOrgHandleRulesFilesRouteImport } from './routes/_app/$orgHandle/rules/files'
import { Route as AppOrgHandleRules0RouteImport } from './routes/_app/$orgHandle/rules/0'
import { Route as AppOrgHandleEventsEventIdRouteImport } from './routes/_app/$orgHandle/events/$eventId'
import { Route as AppOrgHandleAutomationsPreviewRouteImport } from './routes/_app/$orgHandle/automations/preview'
import { Route as AppOrgHandleAutomationsAutomationIdRouteImport } from './routes/_app/$orgHandle/automations/$automationId'
import { Route as AdminAdminResearchNewRouteImport } from './routes/_admin/admin/research/new'
import { Route as AdminAdminResearchRunIdRouteImport } from './routes/_admin/admin/research/$runId'
import { Route as AppOrgHandleRulesCustomIndexRouteImport } from './routes/_app/$orgHandle/rules/custom/index'
import { Route as AppOrgHandleRulesCustomRuleIdRouteImport } from './routes/_app/$orgHandle/rules/custom/$ruleId'

const VouchedRoute = VouchedRouteImport.update({
  id: '/vouched',
  path: '/vouched',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisibilityRoute = AppVisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgHandleRoute = AppOrgHandleRouteImport.update({
  id: '/$orgHandle',
  path: '/$orgHandle',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthAuthorizationServerRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const RequestOwnerRepoRoute = RequestOwnerRepoRouteImport.update({
  id: '/request/$owner/$repo',
  path: '/request/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/step/4',
  path: '/step/4',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/step/3',
  path: '/step/3',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/step/2',
  path: '/step/2',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/step/1',
  path: '/step/1',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ApiV1VouchedRoute = ApiV1VouchedRouteImport.update({
  id: '/api/v1/vouched',
  path: '/api/v1/vouched',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsRunRoute = ApiToolsRunRouteImport.update({
  id: '/api/tools/run',
  path: '/api/tools/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthAppInfoRoute = ApiOauthAppInfoRouteImport.update({
  id: '/api/oauth/app-info',
  path: '/api/oauth/app-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevLoginRoute = ApiDevLoginRouteImport.update({
  id: '/api/dev/login',
  path: '/api/dev/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUsernameRoute = AppUsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDevelopersRoute = AppSettingsDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgHandleVisibilityRoute = AppOrgHandleVisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AppOrgHandleSettingsRoute = AppOrgHandleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AppOrgHandleIntegrationsRoute =
  AppOrgHandleIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AppOrgHandleInsightsRoute = AppOrgHandleInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AppOrgHandleHomeRoute = AppOrgHandleHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AdminAdminReputationRoute = AdminAdminReputationRouteImport.update({
  id: '/admin/reputation',
  path: '/admin/reputation',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceSplatRoute =
  Char91DotwellKnownChar93OauthProtectedResourceSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char91DotwellKnownChar93OauthProtectedResourceRoute,
  } as any)
const Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char91DotwellKnownChar93OauthAuthorizationServerRoute,
  } as any)
const AppOrgHandleRulesRouteRoute = AppOrgHandleRulesRouteRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AppOrgHandleRulesIndexRoute = AppOrgHandleRulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgHandleRulesRouteRoute,
} as any)
const AppOrgHandleEventsIndexRoute = AppOrgHandleEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppOrgHandleRoute,
} as any)
const AppOrgHandleAutomationsIndexRoute =
  AppOrgHandleAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AdminAdminResearchIndexRoute = AdminAdminResearchIndexRouteImport.update({
  id: '/admin/research/',
  path: '/admin/research/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiGithubSignalsStreamRoute = ApiGithubSignalsStreamRouteImport.update({
  id: '/api/github/signals/stream',
  path: '/api/github/signals/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgHandleRulesWorkflowsRoute =
  AppOrgHandleRulesWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AppOrgHandleRulesRouteRoute,
  } as any)
const AppOrgHandleRulesRequestsRoute =
  AppOrgHandleRulesRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AppOrgHandleRulesRouteRoute,
  } as any)
const AppOrgHandleRulesPeopleRoute = AppOrgHandleRulesPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppOrgHandleRulesRouteRoute,
} as any)
const AppOrgHandleRulesMarketplaceRoute =
  AppOrgHandleRulesMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AppOrgHandleRulesRouteRoute,
  } as any)
const AppOrgHandleRulesInstalledRoute =
  AppOrgHandleRulesInstalledRouteImport.update({
    id: '/installed',
    path: '/installed',
    getParentRoute: () => AppOrgHandleRulesRouteRoute,
  } as any)
const AppOrgHandleRulesFilesRoute = AppOrgHandleRulesFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppOrgHandleRulesRouteRoute,
} as any)
const AppOrgHandleRules0Route = AppOrgHandleRules0RouteImport.update({
  id: '/0',
  path: '/0',
  getParentRoute: () => AppOrgHandleRulesRouteRoute,
} as any)
const AppOrgHandleEventsEventIdRoute =
  AppOrgHandleEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AppOrgHandleAutomationsPreviewRoute =
  AppOrgHandleAutomationsPreviewRouteImport.update({
    id: '/automations/preview',
    path: '/automations/preview',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AppOrgHandleAutomationsAutomationIdRoute =
  AppOrgHandleAutomationsAutomationIdRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => AppOrgHandleRoute,
  } as any)
const AdminAdminResearchNewRoute = AdminAdminResearchNewRouteImport.update({
  id: '/admin/research/new',
  path: '/admin/research/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminResearchRunIdRoute = AdminAdminResearchRunIdRouteImport.update({
  id: '/admin/research/$runId',
  path: '/admin/research/$runId',
  getParentRoute: () => AdminRoute,
} as any)
const AppOrgHandleRulesCustomIndexRoute =
  AppOrgHandleRulesCustomIndexRouteImport.update({
    id: '/custom/',
    path: '/custom/',
    getParentRoute: () => AppOrgHandleRulesRouteRoute,
  } as any)
const AppOrgHandleRulesCustomRuleIdRoute =
  AppOrgHandleRulesCustomRuleIdRouteImport.update({
    id: '/custom/$ruleId',
    path: '/custom/$ruleId',
    getParentRoute: () => AppOrgHandleRulesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/vouched': typeof VouchedRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren
  '/$orgHandle': typeof AppOrgHandleRouteWithChildren
  '/automations': typeof AppAutomationsRoute
  '/home': typeof AppHomeRoute
  '/insights': typeof AppInsightsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/visibility': typeof AppVisibilityRoute
  '/api/chat': typeof ApiChatRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/$orgHandle/rules': typeof AppOrgHandleRulesRouteRouteWithChildren
  '/.well-known/oauth-authorization-server/$': typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRoute
  '/admin/reputation': typeof AdminAdminReputationRoute
  '/$orgHandle/home': typeof AppOrgHandleHomeRoute
  '/$orgHandle/insights': typeof AppOrgHandleInsightsRoute
  '/$orgHandle/integrations': typeof AppOrgHandleIntegrationsRoute
  '/$orgHandle/settings': typeof AppOrgHandleSettingsRoute
  '/$orgHandle/visibility': typeof AppOrgHandleVisibilityRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/developers': typeof AppSettingsDevelopersRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/login': typeof ApiDevLoginRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/app-info': typeof ApiOauthAppInfoRoute
  '/api/tools/run': typeof ApiToolsRunRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/vouched': typeof ApiV1VouchedRoute
  '/onboarding/step/1': typeof OnboardingStep1Route
  '/onboarding/step/2': typeof OnboardingStep2Route
  '/onboarding/step/3': typeof OnboardingStep3Route
  '/onboarding/step/4': typeof OnboardingStep4Route
  '/request/$owner/$repo': typeof RequestOwnerRepoRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/admin/research/$runId': typeof AdminAdminResearchRunIdRoute
  '/admin/research/new': typeof AdminAdminResearchNewRoute
  '/$orgHandle/automations/$automationId': typeof AppOrgHandleAutomationsAutomationIdRoute
  '/$orgHandle/automations/preview': typeof AppOrgHandleAutomationsPreviewRoute
  '/$orgHandle/events/$eventId': typeof AppOrgHandleEventsEventIdRoute
  '/$orgHandle/rules/0': typeof AppOrgHandleRules0Route
  '/$orgHandle/rules/files': typeof AppOrgHandleRulesFilesRoute
  '/$orgHandle/rules/installed': typeof AppOrgHandleRulesInstalledRoute
  '/$orgHandle/rules/marketplace': typeof AppOrgHandleRulesMarketplaceRoute
  '/$orgHandle/rules/people': typeof AppOrgHandleRulesPeopleRoute
  '/$orgHandle/rules/requests': typeof AppOrgHandleRulesRequestsRoute
  '/$orgHandle/rules/workflows': typeof AppOrgHandleRulesWorkflowsRoute
  '/api/github/signals/stream': typeof ApiGithubSignalsStreamRoute
  '/admin/research/': typeof AdminAdminResearchIndexRoute
  '/$orgHandle/automations/': typeof AppOrgHandleAutomationsIndexRoute
  '/$orgHandle/events/': typeof AppOrgHandleEventsIndexRoute
  '/$orgHandle/rules/': typeof AppOrgHandleRulesIndexRoute
  '/$orgHandle/rules/custom/$ruleId': typeof AppOrgHandleRulesCustomRuleIdRoute
  '/$orgHandle/rules/custom/': typeof AppOrgHandleRulesCustomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/vouched': typeof VouchedRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren
  '/$orgHandle': typeof AppOrgHandleRouteWithChildren
  '/automations': typeof AppAutomationsRoute
  '/home': typeof AppHomeRoute
  '/insights': typeof AppInsightsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/visibility': typeof AppVisibilityRoute
  '/api/chat': typeof ApiChatRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRoute
  '/admin/reputation': typeof AdminAdminReputationRoute
  '/$orgHandle/home': typeof AppOrgHandleHomeRoute
  '/$orgHandle/insights': typeof AppOrgHandleInsightsRoute
  '/$orgHandle/integrations': typeof AppOrgHandleIntegrationsRoute
  '/$orgHandle/settings': typeof AppOrgHandleSettingsRoute
  '/$orgHandle/visibility': typeof AppOrgHandleVisibilityRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/developers': typeof AppSettingsDevelopersRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/login': typeof ApiDevLoginRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/app-info': typeof ApiOauthAppInfoRoute
  '/api/tools/run': typeof ApiToolsRunRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/vouched': typeof ApiV1VouchedRoute
  '/onboarding/step/1': typeof OnboardingStep1Route
  '/onboarding/step/2': typeof OnboardingStep2Route
  '/onboarding/step/3': typeof OnboardingStep3Route
  '/onboarding/step/4': typeof OnboardingStep4Route
  '/request/$owner/$repo': typeof RequestOwnerRepoRoute
  '/admin': typeof AdminAdminIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/admin/research/$runId': typeof AdminAdminResearchRunIdRoute
  '/admin/research/new': typeof AdminAdminResearchNewRoute
  '/$orgHandle/automations/$automationId': typeof AppOrgHandleAutomationsAutomationIdRoute
  '/$orgHandle/automations/preview': typeof AppOrgHandleAutomationsPreviewRoute
  '/$orgHandle/events/$eventId': typeof AppOrgHandleEventsEventIdRoute
  '/$orgHandle/rules/0': typeof AppOrgHandleRules0Route
  '/$orgHandle/rules/files': typeof AppOrgHandleRulesFilesRoute
  '/$orgHandle/rules/installed': typeof AppOrgHandleRulesInstalledRoute
  '/$orgHandle/rules/marketplace': typeof AppOrgHandleRulesMarketplaceRoute
  '/$orgHandle/rules/people': typeof AppOrgHandleRulesPeopleRoute
  '/$orgHandle/rules/requests': typeof AppOrgHandleRulesRequestsRoute
  '/$orgHandle/rules/workflows': typeof AppOrgHandleRulesWorkflowsRoute
  '/api/github/signals/stream': typeof ApiGithubSignalsStreamRoute
  '/admin/research': typeof AdminAdminResearchIndexRoute
  '/$orgHandle/automations': typeof AppOrgHandleAutomationsIndexRoute
  '/$orgHandle/events': typeof AppOrgHandleEventsIndexRoute
  '/$orgHandle/rules': typeof AppOrgHandleRulesIndexRoute
  '/$orgHandle/rules/custom/$ruleId': typeof AppOrgHandleRulesCustomRuleIdRoute
  '/$orgHandle/rules/custom': typeof AppOrgHandleRulesCustomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/vouched': typeof VouchedRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren
  '/_app/$orgHandle': typeof AppOrgHandleRouteWithChildren
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/visibility': typeof AppVisibilityRoute
  '/api/chat': typeof ApiChatRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_app/$orgHandle/rules': typeof AppOrgHandleRulesRouteRouteWithChildren
  '/.well-known/oauth-authorization-server/$': typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute
  '/.well-known/oauth-protected-resource/$': typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRoute
  '/_admin/admin/reputation': typeof AdminAdminReputationRoute
  '/_app/$orgHandle/home': typeof AppOrgHandleHomeRoute
  '/_app/$orgHandle/insights': typeof AppOrgHandleInsightsRoute
  '/_app/$orgHandle/integrations': typeof AppOrgHandleIntegrationsRoute
  '/_app/$orgHandle/settings': typeof AppOrgHandleSettingsRoute
  '/_app/$orgHandle/visibility': typeof AppOrgHandleVisibilityRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/developers': typeof AppSettingsDevelopersRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/users/$username': typeof AppUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/login': typeof ApiDevLoginRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/oauth/app-info': typeof ApiOauthAppInfoRoute
  '/api/tools/run': typeof ApiToolsRunRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/vouched': typeof ApiV1VouchedRoute
  '/onboarding/step/1': typeof OnboardingStep1Route
  '/onboarding/step/2': typeof OnboardingStep2Route
  '/onboarding/step/3': typeof OnboardingStep3Route
  '/onboarding/step/4': typeof OnboardingStep4Route
  '/request/$owner/$repo': typeof RequestOwnerRepoRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_admin/admin/research/$runId': typeof AdminAdminResearchRunIdRoute
  '/_admin/admin/research/new': typeof AdminAdminResearchNewRoute
  '/_app/$orgHandle/automations/$automationId': typeof AppOrgHandleAutomationsAutomationIdRoute
  '/_app/$orgHandle/automations/preview': typeof AppOrgHandleAutomationsPreviewRoute
  '/_app/$orgHandle/events/$eventId': typeof AppOrgHandleEventsEventIdRoute
  '/_app/$orgHandle/rules/0': typeof AppOrgHandleRules0Route
  '/_app/$orgHandle/rules/files': typeof AppOrgHandleRulesFilesRoute
  '/_app/$orgHandle/rules/installed': typeof AppOrgHandleRulesInstalledRoute
  '/_app/$orgHandle/rules/marketplace': typeof AppOrgHandleRulesMarketplaceRoute
  '/_app/$orgHandle/rules/people': typeof AppOrgHandleRulesPeopleRoute
  '/_app/$orgHandle/rules/requests': typeof AppOrgHandleRulesRequestsRoute
  '/_app/$orgHandle/rules/workflows': typeof AppOrgHandleRulesWorkflowsRoute
  '/api/github/signals/stream': typeof ApiGithubSignalsStreamRoute
  '/_admin/admin/research/': typeof AdminAdminResearchIndexRoute
  '/_app/$orgHandle/automations/': typeof AppOrgHandleAutomationsIndexRoute
  '/_app/$orgHandle/events/': typeof AppOrgHandleEventsIndexRoute
  '/_app/$orgHandle/rules/': typeof AppOrgHandleRulesIndexRoute
  '/_app/$orgHandle/rules/custom/$ruleId': typeof AppOrgHandleRulesCustomRuleIdRoute
  '/_app/$orgHandle/rules/custom/': typeof AppOrgHandleRulesCustomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/login'
    | '/vouched'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/$orgHandle'
    | '/automations'
    | '/home'
    | '/insights'
    | '/integrations'
    | '/rules'
    | '/search'
    | '/settings'
    | '/visibility'
    | '/api/chat'
    | '/api/feedback'
    | '/api/inngest'
    | '/api/mcp'
    | '/oauth/consent'
    | '/$orgHandle/rules'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/admin/reputation'
    | '/$orgHandle/home'
    | '/$orgHandle/insights'
    | '/$orgHandle/integrations'
    | '/$orgHandle/settings'
    | '/$orgHandle/visibility'
    | '/chat/$chatId'
    | '/events/$eventId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/developers'
    | '/settings/general'
    | '/users/$username'
    | '/api/auth/$'
    | '/api/dev/login'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/oauth/app-info'
    | '/api/tools/run'
    | '/api/trpc/$'
    | '/api/v1/vouched'
    | '/onboarding/step/1'
    | '/onboarding/step/2'
    | '/onboarding/step/3'
    | '/onboarding/step/4'
    | '/request/$owner/$repo'
    | '/admin/'
    | '/events/'
    | '/admin/research/$runId'
    | '/admin/research/new'
    | '/$orgHandle/automations/$automationId'
    | '/$orgHandle/automations/preview'
    | '/$orgHandle/events/$eventId'
    | '/$orgHandle/rules/0'
    | '/$orgHandle/rules/files'
    | '/$orgHandle/rules/installed'
    | '/$orgHandle/rules/marketplace'
    | '/$orgHandle/rules/people'
    | '/$orgHandle/rules/requests'
    | '/$orgHandle/rules/workflows'
    | '/api/github/signals/stream'
    | '/admin/research/'
    | '/$orgHandle/automations/'
    | '/$orgHandle/events/'
    | '/$orgHandle/rules/'
    | '/$orgHandle/rules/custom/$ruleId'
    | '/$orgHandle/rules/custom/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/vouched'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/$orgHandle'
    | '/automations'
    | '/home'
    | '/insights'
    | '/integrations'
    | '/rules'
    | '/search'
    | '/settings'
    | '/visibility'
    | '/api/chat'
    | '/api/feedback'
    | '/api/inngest'
    | '/api/mcp'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/admin/reputation'
    | '/$orgHandle/home'
    | '/$orgHandle/insights'
    | '/$orgHandle/integrations'
    | '/$orgHandle/settings'
    | '/$orgHandle/visibility'
    | '/chat/$chatId'
    | '/events/$eventId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/developers'
    | '/settings/general'
    | '/users/$username'
    | '/api/auth/$'
    | '/api/dev/login'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/oauth/app-info'
    | '/api/tools/run'
    | '/api/trpc/$'
    | '/api/v1/vouched'
    | '/onboarding/step/1'
    | '/onboarding/step/2'
    | '/onboarding/step/3'
    | '/onboarding/step/4'
    | '/request/$owner/$repo'
    | '/admin'
    | '/events'
    | '/admin/research/$runId'
    | '/admin/research/new'
    | '/$orgHandle/automations/$automationId'
    | '/$orgHandle/automations/preview'
    | '/$orgHandle/events/$eventId'
    | '/$orgHandle/rules/0'
    | '/$orgHandle/rules/files'
    | '/$orgHandle/rules/installed'
    | '/$orgHandle/rules/marketplace'
    | '/$orgHandle/rules/people'
    | '/$orgHandle/rules/requests'
    | '/$orgHandle/rules/workflows'
    | '/api/github/signals/stream'
    | '/admin/research'
    | '/$orgHandle/automations'
    | '/$orgHandle/events'
    | '/$orgHandle/rules'
    | '/$orgHandle/rules/custom/$ruleId'
    | '/$orgHandle/rules/custom'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/_admin'
    | '/_app'
    | '/login'
    | '/vouched'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_app/$orgHandle'
    | '/_app/automations'
    | '/_app/home'
    | '/_app/insights'
    | '/_app/integrations'
    | '/_app/rules'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/visibility'
    | '/api/chat'
    | '/api/feedback'
    | '/api/inngest'
    | '/api/mcp'
    | '/oauth/consent'
    | '/_app/$orgHandle/rules'
    | '/.well-known/oauth-authorization-server/$'
    | '/.well-known/oauth-protected-resource/$'
    | '/_admin/admin/reputation'
    | '/_app/$orgHandle/home'
    | '/_app/$orgHandle/insights'
    | '/_app/$orgHandle/integrations'
    | '/_app/$orgHandle/settings'
    | '/_app/$orgHandle/visibility'
    | '/_app/chat/$chatId'
    | '/_app/events/$eventId'
    | '/_app/settings/account'
    | '/_app/settings/billing'
    | '/_app/settings/developers'
    | '/_app/settings/general'
    | '/_app/users/$username'
    | '/api/auth/$'
    | '/api/dev/login'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/oauth/app-info'
    | '/api/tools/run'
    | '/api/trpc/$'
    | '/api/v1/vouched'
    | '/onboarding/step/1'
    | '/onboarding/step/2'
    | '/onboarding/step/3'
    | '/onboarding/step/4'
    | '/request/$owner/$repo'
    | '/_admin/admin/'
    | '/_app/events/'
    | '/_admin/admin/research/$runId'
    | '/_admin/admin/research/new'
    | '/_app/$orgHandle/automations/$automationId'
    | '/_app/$orgHandle/automations/preview'
    | '/_app/$orgHandle/events/$eventId'
    | '/_app/$orgHandle/rules/0'
    | '/_app/$orgHandle/rules/files'
    | '/_app/$orgHandle/rules/installed'
    | '/_app/$orgHandle/rules/marketplace'
    | '/_app/$orgHandle/rules/people'
    | '/_app/$orgHandle/rules/requests'
    | '/_app/$orgHandle/rules/workflows'
    | '/api/github/signals/stream'
    | '/_admin/admin/research/'
    | '/_app/$orgHandle/automations/'
    | '/_app/$orgHandle/events/'
    | '/_app/$orgHandle/rules/'
    | '/_app/$orgHandle/rules/custom/$ruleId'
    | '/_app/$orgHandle/rules/custom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  VouchedRoute: typeof VouchedRoute
  Char91DotwellKnownChar93OauthAuthorizationServerRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiMcpRoute: typeof ApiMcpRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDevLoginRoute: typeof ApiDevLoginRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiOauthAppInfoRoute: typeof ApiOauthAppInfoRoute
  ApiToolsRunRoute: typeof ApiToolsRunRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiV1VouchedRoute: typeof ApiV1VouchedRoute
  RequestOwnerRepoRoute: typeof RequestOwnerRepoRoute
  ApiGithubSignalsStreamRoute: typeof ApiGithubSignalsStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouched': {
      id: '/vouched'
      path: '/vouched'
      fullPath: '/vouched'
      preLoaderRoute: typeof VouchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/visibility': {
      id: '/_app/visibility'
      path: '/visibility'
      fullPath: '/visibility'
      preLoaderRoute: typeof AppVisibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgHandle': {
      id: '/_app/$orgHandle'
      path: '/$orgHandle'
      fullPath: '/$orgHandle'
      preLoaderRoute: typeof AppOrgHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/request/$owner/$repo': {
      id: '/request/$owner/$repo'
      path: '/request/$owner/$repo'
      fullPath: '/request/$owner/$repo'
      preLoaderRoute: typeof RequestOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step/4': {
      id: '/onboarding/step/4'
      path: '/step/4'
      fullPath: '/onboarding/step/4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/step/3': {
      id: '/onboarding/step/3'
      path: '/step/3'
      fullPath: '/onboarding/step/3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/step/2': {
      id: '/onboarding/step/2'
      path: '/step/2'
      fullPath: '/onboarding/step/2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/step/1': {
      id: '/onboarding/step/1'
      path: '/step/1'
      fullPath: '/onboarding/step/1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/api/v1/vouched': {
      id: '/api/v1/vouched'
      path: '/api/v1/vouched'
      fullPath: '/api/v1/vouched'
      preLoaderRoute: typeof ApiV1VouchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/run': {
      id: '/api/tools/run'
      path: '/api/tools/run'
      fullPath: '/api/tools/run'
      preLoaderRoute: typeof ApiToolsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/app-info': {
      id: '/api/oauth/app-info'
      path: '/api/oauth/app-info'
      fullPath: '/api/oauth/app-info'
      preLoaderRoute: typeof ApiOauthAppInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/login': {
      id: '/api/dev/login'
      path: '/api/dev/login'
      fullPath: '/api/dev/login'
      preLoaderRoute: typeof ApiDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/$username': {
      id: '/_app/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AppUsersUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/developers': {
      id: '/_app/settings/developers'
      path: '/developers'
      fullPath: '/settings/developers'
      preLoaderRoute: typeof AppSettingsDevelopersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgHandle/visibility': {
      id: '/_app/$orgHandle/visibility'
      path: '/visibility'
      fullPath: '/$orgHandle/visibility'
      preLoaderRoute: typeof AppOrgHandleVisibilityRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/settings': {
      id: '/_app/$orgHandle/settings'
      path: '/settings'
      fullPath: '/$orgHandle/settings'
      preLoaderRoute: typeof AppOrgHandleSettingsRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/integrations': {
      id: '/_app/$orgHandle/integrations'
      path: '/integrations'
      fullPath: '/$orgHandle/integrations'
      preLoaderRoute: typeof AppOrgHandleIntegrationsRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/insights': {
      id: '/_app/$orgHandle/insights'
      path: '/insights'
      fullPath: '/$orgHandle/insights'
      preLoaderRoute: typeof AppOrgHandleInsightsRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/home': {
      id: '/_app/$orgHandle/home'
      path: '/home'
      fullPath: '/$orgHandle/home'
      preLoaderRoute: typeof AppOrgHandleHomeRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_admin/admin/reputation': {
      id: '/_admin/admin/reputation'
      path: '/admin/reputation'
      fullPath: '/admin/reputation'
      preLoaderRoute: typeof AdminAdminReputationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource/$': {
      id: '/.well-known/oauth-protected-resource/$'
      path: '/$'
      fullPath: '/.well-known/oauth-protected-resource/$'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRouteImport
      parentRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
    }
    '/.well-known/oauth-authorization-server/$': {
      id: '/.well-known/oauth-authorization-server/$'
      path: '/$'
      fullPath: '/.well-known/oauth-authorization-server/$'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRouteImport
      parentRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
    }
    '/_app/$orgHandle/rules': {
      id: '/_app/$orgHandle/rules'
      path: '/rules'
      fullPath: '/$orgHandle/rules'
      preLoaderRoute: typeof AppOrgHandleRulesRouteRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/rules/': {
      id: '/_app/$orgHandle/rules/'
      path: '/'
      fullPath: '/$orgHandle/rules/'
      preLoaderRoute: typeof AppOrgHandleRulesIndexRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/events/': {
      id: '/_app/$orgHandle/events/'
      path: '/events'
      fullPath: '/$orgHandle/events/'
      preLoaderRoute: typeof AppOrgHandleEventsIndexRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/automations/': {
      id: '/_app/$orgHandle/automations/'
      path: '/automations'
      fullPath: '/$orgHandle/automations/'
      preLoaderRoute: typeof AppOrgHandleAutomationsIndexRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_admin/admin/research/': {
      id: '/_admin/admin/research/'
      path: '/admin/research'
      fullPath: '/admin/research/'
      preLoaderRoute: typeof AdminAdminResearchIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/github/signals/stream': {
      id: '/api/github/signals/stream'
      path: '/api/github/signals/stream'
      fullPath: '/api/github/signals/stream'
      preLoaderRoute: typeof ApiGithubSignalsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$orgHandle/rules/workflows': {
      id: '/_app/$orgHandle/rules/workflows'
      path: '/workflows'
      fullPath: '/$orgHandle/rules/workflows'
      preLoaderRoute: typeof AppOrgHandleRulesWorkflowsRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/rules/requests': {
      id: '/_app/$orgHandle/rules/requests'
      path: '/requests'
      fullPath: '/$orgHandle/rules/requests'
      preLoaderRoute: typeof AppOrgHandleRulesRequestsRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/rules/people': {
      id: '/_app/$orgHandle/rules/people'
      path: '/people'
      fullPath: '/$orgHandle/rules/people'
      preLoaderRoute: typeof AppOrgHandleRulesPeopleRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/rules/marketplace': {
      id: '/_app/$orgHandle/rules/marketplace'
      path: '/marketplace'
      fullPath: '/$orgHandle/rules/marketplace'
      preLoaderRoute: typeof AppOrgHandleRulesMarketplaceRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/rules/installed': {
      id: '/_app/$orgHandle/rules/installed'
      path: '/installed'
      fullPath: '/$orgHandle/rules/installed'
      preLoaderRoute: typeof AppOrgHandleRulesInstalledRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/rules/files': {
      id: '/_app/$orgHandle/rules/files'
      path: '/files'
      fullPath: '/$orgHandle/rules/files'
      preLoaderRoute: typeof AppOrgHandleRulesFilesRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/rules/0': {
      id: '/_app/$orgHandle/rules/0'
      path: '/0'
      fullPath: '/$orgHandle/rules/0'
      preLoaderRoute: typeof AppOrgHandleRules0RouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/events/$eventId': {
      id: '/_app/$orgHandle/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/$orgHandle/events/$eventId'
      preLoaderRoute: typeof AppOrgHandleEventsEventIdRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/automations/preview': {
      id: '/_app/$orgHandle/automations/preview'
      path: '/automations/preview'
      fullPath: '/$orgHandle/automations/preview'
      preLoaderRoute: typeof AppOrgHandleAutomationsPreviewRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_app/$orgHandle/automations/$automationId': {
      id: '/_app/$orgHandle/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/$orgHandle/automations/$automationId'
      preLoaderRoute: typeof AppOrgHandleAutomationsAutomationIdRouteImport
      parentRoute: typeof AppOrgHandleRoute
    }
    '/_admin/admin/research/new': {
      id: '/_admin/admin/research/new'
      path: '/admin/research/new'
      fullPath: '/admin/research/new'
      preLoaderRoute: typeof AdminAdminResearchNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/research/$runId': {
      id: '/_admin/admin/research/$runId'
      path: '/admin/research/$runId'
      fullPath: '/admin/research/$runId'
      preLoaderRoute: typeof AdminAdminResearchRunIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/$orgHandle/rules/custom/': {
      id: '/_app/$orgHandle/rules/custom/'
      path: '/custom'
      fullPath: '/$orgHandle/rules/custom/'
      preLoaderRoute: typeof AppOrgHandleRulesCustomIndexRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
    '/_app/$orgHandle/rules/custom/$ruleId': {
      id: '/_app/$orgHandle/rules/custom/$ruleId'
      path: '/custom/$ruleId'
      fullPath: '/$orgHandle/rules/custom/$ruleId'
      preLoaderRoute: typeof AppOrgHandleRulesCustomRuleIdRouteImport
      parentRoute: typeof AppOrgHandleRulesRouteRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminReputationRoute: typeof AdminAdminReputationRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminResearchRunIdRoute: typeof AdminAdminResearchRunIdRoute
  AdminAdminResearchNewRoute: typeof AdminAdminResearchNewRoute
  AdminAdminResearchIndexRoute: typeof AdminAdminResearchIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminReputationRoute: AdminAdminReputationRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminResearchRunIdRoute: AdminAdminResearchRunIdRoute,
  AdminAdminResearchNewRoute: AdminAdminResearchNewRoute,
  AdminAdminResearchIndexRoute: AdminAdminResearchIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppOrgHandleRulesRouteRouteChildren {
  AppOrgHandleRules0Route: typeof AppOrgHandleRules0Route
  AppOrgHandleRulesFilesRoute: typeof AppOrgHandleRulesFilesRoute
  AppOrgHandleRulesInstalledRoute: typeof AppOrgHandleRulesInstalledRoute
  AppOrgHandleRulesMarketplaceRoute: typeof AppOrgHandleRulesMarketplaceRoute
  AppOrgHandleRulesPeopleRoute: typeof AppOrgHandleRulesPeopleRoute
  AppOrgHandleRulesRequestsRoute: typeof AppOrgHandleRulesRequestsRoute
  AppOrgHandleRulesWorkflowsRoute: typeof AppOrgHandleRulesWorkflowsRoute
  AppOrgHandleRulesIndexRoute: typeof AppOrgHandleRulesIndexRoute
  AppOrgHandleRulesCustomRuleIdRoute: typeof AppOrgHandleRulesCustomRuleIdRoute
  AppOrgHandleRulesCustomIndexRoute: typeof AppOrgHandleRulesCustomIndexRoute
}

const AppOrgHandleRulesRouteRouteChildren: AppOrgHandleRulesRouteRouteChildren =
  {
    AppOrgHandleRules0Route: AppOrgHandleRules0Route,
    AppOrgHandleRulesFilesRoute: AppOrgHandleRulesFilesRoute,
    AppOrgHandleRulesInstalledRoute: AppOrgHandleRulesInstalledRoute,
    AppOrgHandleRulesMarketplaceRoute: AppOrgHandleRulesMarketplaceRoute,
    AppOrgHandleRulesPeopleRoute: AppOrgHandleRulesPeopleRoute,
    AppOrgHandleRulesRequestsRoute: AppOrgHandleRulesRequestsRoute,
    AppOrgHandleRulesWorkflowsRoute: AppOrgHandleRulesWorkflowsRoute,
    AppOrgHandleRulesIndexRoute: AppOrgHandleRulesIndexRoute,
    AppOrgHandleRulesCustomRuleIdRoute: AppOrgHandleRulesCustomRuleIdRoute,
    AppOrgHandleRulesCustomIndexRoute: AppOrgHandleRulesCustomIndexRoute,
  }

const AppOrgHandleRulesRouteRouteWithChildren =
  AppOrgHandleRulesRouteRoute._addFileChildren(
    AppOrgHandleRulesRouteRouteChildren,
  )

interface AppOrgHandleRouteChildren {
  AppOrgHandleRulesRouteRoute: typeof AppOrgHandleRulesRouteRouteWithChildren
  AppOrgHandleHomeRoute: typeof AppOrgHandleHomeRoute
  AppOrgHandleInsightsRoute: typeof AppOrgHandleInsightsRoute
  AppOrgHandleIntegrationsRoute: typeof AppOrgHandleIntegrationsRoute
  AppOrgHandleSettingsRoute: typeof AppOrgHandleSettingsRoute
  AppOrgHandleVisibilityRoute: typeof AppOrgHandleVisibilityRoute
  AppOrgHandleAutomationsAutomationIdRoute: typeof AppOrgHandleAutomationsAutomationIdRoute
  AppOrgHandleAutomationsPreviewRoute: typeof AppOrgHandleAutomationsPreviewRoute
  AppOrgHandleEventsEventIdRoute: typeof AppOrgHandleEventsEventIdRoute
  AppOrgHandleAutomationsIndexRoute: typeof AppOrgHandleAutomationsIndexRoute
  AppOrgHandleEventsIndexRoute: typeof AppOrgHandleEventsIndexRoute
}

const AppOrgHandleRouteChildren: AppOrgHandleRouteChildren = {
  AppOrgHandleRulesRouteRoute: AppOrgHandleRulesRouteRouteWithChildren,
  AppOrgHandleHomeRoute: AppOrgHandleHomeRoute,
  AppOrgHandleInsightsRoute: AppOrgHandleInsightsRoute,
  AppOrgHandleIntegrationsRoute: AppOrgHandleIntegrationsRoute,
  AppOrgHandleSettingsRoute: AppOrgHandleSettingsRoute,
  AppOrgHandleVisibilityRoute: AppOrgHandleVisibilityRoute,
  AppOrgHandleAutomationsAutomationIdRoute:
    AppOrgHandleAutomationsAutomationIdRoute,
  AppOrgHandleAutomationsPreviewRoute: AppOrgHandleAutomationsPreviewRoute,
  AppOrgHandleEventsEventIdRoute: AppOrgHandleEventsEventIdRoute,
  AppOrgHandleAutomationsIndexRoute: AppOrgHandleAutomationsIndexRoute,
  AppOrgHandleEventsIndexRoute: AppOrgHandleEventsIndexRoute,
}

const AppOrgHandleRouteWithChildren = AppOrgHandleRoute._addFileChildren(
  AppOrgHandleRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsDevelopersRoute: typeof AppSettingsDevelopersRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsDevelopersRoute: AppSettingsDevelopersRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppOrgHandleRoute: typeof AppOrgHandleRouteWithChildren
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppVisibilityRoute: typeof AppVisibilityRoute
  AppChatChatIdRoute: typeof AppChatChatIdRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppUsersUsernameRoute: typeof AppUsersUsernameRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgHandleRoute: AppOrgHandleRouteWithChildren,
  AppAutomationsRoute: AppAutomationsRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppRulesRoute: AppRulesRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppVisibilityRoute: AppVisibilityRoute,
  AppChatChatIdRoute: AppChatChatIdRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppUsersUsernameRoute: AppUsersUsernameRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface Char91DotwellKnownChar93OauthAuthorizationServerRouteChildren {
  Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute
}

const Char91DotwellKnownChar93OauthAuthorizationServerRouteChildren: Char91DotwellKnownChar93OauthAuthorizationServerRouteChildren =
  {
    Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute:
      Char91DotwellKnownChar93OauthAuthorizationServerSplatRoute,
  }

const Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren =
  Char91DotwellKnownChar93OauthAuthorizationServerRoute._addFileChildren(
    Char91DotwellKnownChar93OauthAuthorizationServerRouteChildren,
  )

interface Char91DotwellKnownChar93OauthProtectedResourceRouteChildren {
  Char91DotwellKnownChar93OauthProtectedResourceSplatRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceSplatRoute
}

const Char91DotwellKnownChar93OauthProtectedResourceRouteChildren: Char91DotwellKnownChar93OauthProtectedResourceRouteChildren =
  {
    Char91DotwellKnownChar93OauthProtectedResourceSplatRoute:
      Char91DotwellKnownChar93OauthProtectedResourceSplatRoute,
  }

const Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren =
  Char91DotwellKnownChar93OauthProtectedResourceRoute._addFileChildren(
    Char91DotwellKnownChar93OauthProtectedResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  VouchedRoute: VouchedRoute,
  Char91DotwellKnownChar93OauthAuthorizationServerRoute:
    Char91DotwellKnownChar93OauthAuthorizationServerRouteWithChildren,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiMcpRoute: ApiMcpRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDevLoginRoute: ApiDevLoginRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubInstallRoute: ApiGithubInstallRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiOauthAppInfoRoute: ApiOauthAppInfoRoute,
  ApiToolsRunRoute: ApiToolsRunRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiV1VouchedRoute: ApiV1VouchedRoute,
  RequestOwnerRepoRoute: RequestOwnerRepoRoute,
  ApiGithubSignalsStreamRoute: ApiGithubSignalsStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
