/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiGithubWebhookRouteImport } from './routes/api.github.webhook'
import { Route as ApiGithubCallbackRouteImport } from './routes/api.github.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/automations': typeof AppAutomationsRoute
  '/events': typeof AppEventsRoute
  '/home': typeof AppHomeRoute
  '/insights': typeof AppInsightsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/automations': typeof AppAutomationsRoute
  '/events': typeof AppEventsRoute
  '/home': typeof AppHomeRoute
  '/insights': typeof AppInsightsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/rules': typeof AppRulesRoute
  '/search': typeof AppSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/search': typeof AppSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/automations'
    | '/events'
    | '/home'
    | '/insights'
    | '/integrations'
    | '/rules'
    | '/search'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/webhook'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/automations'
    | '/events'
    | '/home'
    | '/insights'
    | '/integrations'
    | '/rules'
    | '/search'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/webhook'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/automations'
    | '/_app/events'
    | '/_app/home'
    | '/_app/insights'
    | '/_app/integrations'
    | '/_app/rules'
    | '/_app/search'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/webhook'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSearchRoute: typeof AppSearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppEventsRoute: AppEventsRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppRulesRoute: AppRulesRoute,
  AppSearchRoute: AppSearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
